overrides:
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  express@<4.19.2: '>=4.19.2'
  braces@<3.0.3: '>=3.0.3'
  micromatch@<4.0.8: '>=4.0.8'
  webpack@>=5.0.0-alpha.0 <5.94.0: '>=5.94.0'
  body-parser@<1.20.3: '>=1.20.3'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
  express@<4.20.0: '>=4.20.0'
  nanoid@<3.3.8: '>=3.3.8'
  path-to-regexp@<0.1.10: '>=0.1.10'
  cookie@<0.7.0: '>=0.7.0'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  path-to-regexp@<0.1.12: '>=0.1.12'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
